public with sharing class LoggerConstants {

    public static final String OBJECT_LOG = 'Log__c';

    public static final String CUSTOM_SETTING_ADMINISTRATOR = 'Administrator__c';
    public static final String CUSTOM_METADATA_TYPE_LOGGER_SETTINGS = 'Logger_Settings__mdt';
    public static final String GLOBAL_SETTING = 'Global_Setting';

    public static final String RECORD_TYPE_LABEL_DEBUG_LOG = 'Debug Log';
    public static final String RECORD_TYPE_LABEL_EXECUTION_LOG = 'Execution Log';
    public static final String RECORD_TYPE_LABEL_EXCEPTION_LOG = 'Exception Log';
}